jobs:
  - name: benchmark_golang
    type: runCLI
    steps:
      - IN: golang_bench
      - TASK:
        - script: ./IN/golang_bench/gitRepo/runBenchmark.sh
    on_success:
      - script: ./IN/golang_bench/gitRepo/onSuccess.sh
    on_failure:
      - script: echo 'Failed job .... :('

  - name: golang_benchmarks_runCI
    type: runCI
    steps:
      - IN: 12hour-trigger

